Feature/pd 9 responsive development
silent-improvement/silent-improvement-landing-page pull request #2
Opened 2024-04-03 22:20 UTC by silent-improvement

2024-04-04 02:20 UTC, phillygogo requested changes

2024-04-04 02:20 UTC, phillygogo commented on scss/partials/_content.scss
> +    @include x-large-container;
Remove unneeded code

2024-04-04 02:20 UTC, phillygogo commented on scss/partials/_content.scss
>    &__portrait {
remove unused Portrait

2024-04-04 02:20 UTC, phillygogo commented on scss/partials/_content.scss
> +  @include breakpoint-lg-down {
Duplicate code here too, unneeded breakpoints. Set a bunch of default styles then only change the things you need when going down through the breakpoints,

2024-04-04 02:20 UTC, phillygogo commented on pages/about.html
>          <div class="content__content">
This isn't correct BEM. Maybe it should be `content__content-wrapper`?

2024-04-04 02:20 UTC, phillygogo commented on index.html
> +                        <span class="card-button__content cantarell-regular">
use a mixin instead of adding classes to every row. Remove all these classes for fonts and replace with the new way I showed you

2024-05-13 01:45 UTC, phillygogo requested changes

2024-05-13 01:45 UTC, phillygogo commented on index.html
> +            <h3>
test this with screen reader, see how it reads it out. then try changing it tso the H3 is in the anchor

2024-05-13 01:45 UTC, phillygogo commented on scss/partials/_header.scss
> +    @include breakpoint-ml-down {
Review hovers on tablet and mobile

2024-05-13 01:45 UTC, phillygogo commented on scss/partials/_header.scss
>      @include breakpoint-sm-down {
remove hovers on Tablet and Mobile

2024-05-13 01:45 UTC, phillygogo commented on scss/_utilities.scss
> +@mixin x-large-heading() {
move all typography related stuff out of _utilities  and put them in the Typography file.

Then move all Utilities out, and put them in the Utilities file.

2024-05-13 01:45 UTC, phillygogo commented on scss/_utilities.scss
> +  @include breakpoint-lg-down() {
unneeded

2024-05-13 01:45 UTC, phillygogo commented on scss/_utilities.scss
> +  @include breakpoint-sm-down() {
unneeded

2024-05-13 03:52 UTC, silent-improvement commented on index.html
> +            <h3>
Tested with screen reader and made change after reading about best practice

2024-05-19 22:07 UTC, phillygogo requested changes

2024-05-19 22:07 UTC, phillygogo commented on scss/partials/_header.scss
>        display: flex;
remove duplicate

2024-05-19 22:07 UTC, phillygogo commented on scss/partials/_footer.scss
> +    @include breakpoint-sm-down {
unneeded duplicates through breakpoints

2024-05-19 22:07 UTC, phillygogo commented on scss/partials/_header.scss
> +      margin-right: 3rem;
not needed duplicate

2024-05-19 22:07 UTC, phillygogo commented on scss/partials/_header.scss
> +      width: 100%;
dupliacate

2024-05-19 22:07 UTC, phillygogo commented on scss/partials/_header.scss
>        width: 100%;
duplicate

2024-05-21 02:21 UTC, merged